twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        REACT_APP_AMAZON_URL: '%env(resolve:REACT_APP_AMAZON_URL)%'
