export const datos = [
    {
        id: 355,
        name: 'AL',
        displayText: 'AL(+355)',
        locale: 'es-ES',
        flag: '/img/flags/al.svg',
    },
    {
        id: 49,
        name: 'DE',
        displayText: 'DE(+49)',
        locale: 'es-ES',
        flag: '/img/flags/de.svg',
    },
    {
        id: 376,
        name: 'AD',
        displayText: 'AD(+376)',
        locale: 'es-ES',
        flag: '/img/flags/ad.svg',
    },
    {
        id: 244,
        name: 'AO',
        displayText: 'AO(+244)',
        locale: 'es-ES',
        flag: '/img/flags/ao.svg',
    },
    {
        id: 966,
        name: 'SA',
        displayText: 'SA(+966)',
        locale: 'es-ES',
        flag: '/img/flags/sa.svg',
    },
    {
        id: 54,
        name: 'AR',
        displayText: 'AR(+54)',
        locale: 'es-ES',
        flag: '/img/flags/ar.svg',
    },
    {
        id: 374,
        name: 'AM',
        displayText: 'AM(+374)',
        locale: 'es-ES',
        flag: '/img/flags/am.svg',
    },
    {
        id: 97,
        name: 'AW',
        displayText: 'AW(+97)',
        locale: 'es-ES',
        flag: '/img/flags/aw.svg',
    },
    {
        id: 61,
        name: 'AU',
        displayText: 'AU(+61)',
        locale: 'es-ES',
        flag: '/img/flags/au.svg',
    },
    {
        id: 43,
        name: 'AT',
        displayText: 'AT(+43)',
        locale: 'es-ES',
        flag: '/img/flags/at.svg',
    },
    {
        id: 1002,
        name: 'BS',
        displayText: 'BS(+1002)',
        locale: 'es-ES',
        flag: '/img/flags/bs.svg',
    },
    {
        id: 880,
        name: 'BD',
        displayText: 'BD(+880)',
        locale: 'es-ES',
        flag: '/img/flags/bd.svg',
    },
    {
        id: 1246,
        name: 'BB',
        displayText: 'BB(+1246)',
        locale: 'es-ES',
        flag: '/img/flags/bb.svg',
    },
    {
        id: 501,
        name: 'BZ',
        displayText: 'BZ(+501)',
        locale: 'es-ES',
        flag: '/img/flags/bz.svg',
    },
    {
        id: 229,
        name: 'BJ',
        displayText: 'BJ(+229)',
        locale: 'es-ES',
        flag: '/img/flags/bj.svg',
    },
    {
        id: 591,
        name: 'BO',
        displayText: 'BO(+591)',
        locale: 'es-ES',
        flag: '/img/flags/bo.svg',
    },
    {
        id: 387,
        name: 'BA',
        displayText: 'BA(+387)',
        locale: 'es-ES',
        flag: '/img/flags/ba.svg',
    },
    {
        id: 267,
        name: 'BW',
        displayText: 'BW(+267)',
        locale: 'es-ES',
        flag: '/img/flags/bw.svg',
    },
    {
        id: 55,
        name: 'BR',
        displayText: 'BR(+55)',
        locale: 'es-ES',
        flag: '/img/flags/br.svg',
    },
    {
        id: 673,
        name: 'BN',
        displayText: 'BN(+673)',
        locale: 'es-ES',
        flag: '/img/flags/bn.svg',
    },
    {
        id: 359,
        name: 'BG',
        displayText: 'BG(+359)',
        locale: 'es-ES',
        flag: '/img/flags/bg.svg',
    },
    {
        id: 226,
        name: 'BF',
        displayText: 'BF(+226)',
        locale: 'es-ES',
        flag: '/img/flags/bf.svg',
    },
    {
        id: 257,
        name: 'BI',
        displayText: 'BI(+257)',
        locale: 'es-ES',
        flag: '/img/flags/bi.svg',
    },
    {
        id: 32,
        name: 'BE',
        displayText: 'BE(+32)',
        locale: 'es-ES',
        flag: '/img/flags/be.svg',
    },
    {
        id: 238,
        name: 'CV',
        displayText: 'CV(+238)',
        locale: 'es-ES',
        flag: '/img/flags/cv.svg',
    },
    {
        id: 237,
        name: 'CM',
        displayText: 'CM(+237)',
        locale: 'es-ES',
        flag: '/img/flags/cm.svg',
    },
    {
        id: 1,
        name: 'CA',
        displayText: 'CA(+1)',
        locale: 'es-ES',
        flag: '/img/flags/ca.svg',
    },
    {
        id: 235,
        name: 'TD',
        displayText: 'TD(+235)',
        locale: 'es-ES',
        flag: '/img/flags/td.svg',
    },
    {
        id: 56,
        name: 'CL',
        displayText: 'CL(+56)',
        locale: 'es-ES',
        flag: '/img/flags/cl.svg',
    },
    {
        id: 86,
        name: 'CN',
        displayText: 'CN(+86)',
        locale: 'es-ES',
        flag: '/img/flags/cn.svg',
    },
    {
        id: 357,
        name: 'CY',
        displayText: 'CY(+357)',
        locale: 'es-ES',
        flag: '/img/flags/cy.svg',
    },
    {
        id: 57,
        name: 'CO',
        displayText: 'CO(+57)',
        locale: 'es-ES',
        flag: '/img/flags/co.svg',
    },
    {
        id: 850,
        name: 'KP',
        displayText: 'KP(+850)',
        locale: 'es-ES',
        flag: '/img/flags/kp.svg',
    },
    {
        id: 506,
        name: 'CR',
        displayText: 'CR(+506)',
        locale: 'es-ES',
        flag: '/img/flags/cr.svg',
    },
    {
        id: 225,
        name: 'CI',
        displayText: 'CI(+225)',
        locale: 'es-ES',
        flag: '/img/flags/ci.svg',
    },
    {
        id: 385,
        name: 'HR',
        displayText: 'HR(+385)',
        locale: 'es-ES',
        flag: '/img/flags/hr.svg',
    },
    {
        id: 53,
        name: 'CU',
        displayText: 'CU(+53)',
        locale: 'es-ES',
        flag: '/img/flags/cu.svg',
    },
    {
        id: 45,
        name: 'DK',
        displayText: 'DK(+45)',
        locale: 'es-ES',
        flag: '/img/flags/dk.svg',
    },
    {
        id: 1007,
        name: 'DM',
        displayText: 'DM(+1007)',
        locale: 'es-ES',
        flag: '/img/flags/dm.svg',
    },
    {
        id: 593,
        name: 'EC',
        displayText: 'EC(+593)',
        locale: 'es-ES',
        flag: '/img/flags/ec.svg',
    },
    {
        id: 20,
        name: 'EG',
        displayText: 'EG(+20)',
        locale: 'es-ES',
        flag: '/img/flags/eg.svg',
    },
    {
        id: 503,
        name: 'SV',
        displayText: 'SV(+503)',
        locale: 'es-ES',
        flag: '/img/flags/sv.svg',
    },
    {
        id: 421,
        name: 'SK',
        displayText: 'SK(+421)',
        locale: 'es-ES',
        flag: '/img/flags/sk.svg',
    },
    {
        id: 34,
        name: 'ES',
        displayText: 'ES(+34)',
        locale: 'es-ES',
        flag: '/img/flags/es.svg',
    },
    {
        id: 1,
        name: 'US',
        displayText: 'US(+1)',
        locale: 'es-ES',
        flag: '/img/flags/us.svg',
    },
    {
        id: 372,
        name: 'EE',
        displayText: 'EE(+372)',
        locale: 'es-ES',
        flag: '/img/flags/ee.svg',
    },
    {
        id: 63,
        name: 'PH',
        displayText: 'PH(+63)',
        locale: 'es-ES',
        flag: '/img/flags/ph.svg',
    },
    {
        id: 358,
        name: 'FI',
        displayText: 'FI(+358)',
        locale: 'es-ES',
        flag: '/img/flags/fi.svg',
    },
    {
        id: 33,
        name: 'FR',
        displayText: 'FR(+33)',
        locale: 'es-ES',
        flag: '/img/flags/fr.svg',
    },
    {
        id: 220,
        name: 'GM',
        displayText: 'GM(+220)',
        locale: 'es-ES',
        flag: '/img/flags/gm.svg',
    },
    {
        id: 995,
        name: 'GE',
        displayText: 'GE(+995)',
        locale: 'es-ES',
        flag: '/img/flags/ge.svg',
    },
    {
        id: 233,
        name: 'GH',
        displayText: 'GH(+233)',
        locale: 'es-ES',
        flag: '/img/flags/gh.svg',
    },
    {
        id: 350,
        name: 'GI',
        displayText: 'GI(+350)',
        locale: 'es-ES',
        flag: '/img/flags/gi.svg',
    },
    {
        id: 1009,
        name: 'GD',
        displayText: 'GD(+1009)',
        locale: 'es-ES',
        flag: '/img/flags/gd.svg',
    },
    {
        id: 30,
        name: 'GR',
        displayText: 'GR(+30)',
        locale: 'es-ES',
        flag: '/img/flags/gr.svg',
    },
    {
        id: 590,
        name: 'GP',
        displayText: 'GP(+590)',
        locale: 'es-ES',
        flag: '/img/flags/gp.svg',
    },
    {
        id: 1671,
        name: 'GU',
        displayText: 'GU(+1671)',
        locale: 'es-ES',
        flag: '/img/flags/gu.svg',
    },
    {
        id: 502,
        name: 'GT',
        displayText: 'GT(+502)',
        locale: 'es-ES',
        flag: '/img/flags/gt.svg',
    },
    {
        id: 224,
        name: 'GN',
        displayText: 'GN(+224)',
        locale: 'es-ES',
        flag: '/img/flags/gn.svg',
    },
    {
        id: 240,
        name: 'GQ',
        displayText: 'GQ(+240)',
        locale: 'es-ES',
        flag: '/img/flags/gq.svg',
    },
    {
        id: 245,
        name: 'GW',
        displayText: 'GW(+245)',
        locale: 'es-ES',
        flag: '/img/flags/gw.svg',
    },
    {
        id: 592,
        name: 'GY',
        displayText: 'GY(+592)',
        locale: 'es-ES',
        flag: '/img/flags/gy.svg',
    },
    {
        id: 504,
        name: 'HN',
        displayText: 'HN(+504)',
        locale: 'es-ES',
        flag: '/img/flags/hn.svg',
    },
    {
        id: 852,
        name: 'HK',
        displayText: 'HK(+852)',
        locale: 'es-ES',
        flag: '/img/flags/hk.svg',
    },
    {
        id: 91,
        name: 'IN',
        displayText: 'IN(+91)',
        locale: 'es-ES',
        flag: '/img/flags/in.svg',
    },
    {
        id: 62,
        name: 'ID',
        displayText: 'ID(+62)',
        locale: 'es-ES',
        flag: '/img/flags/id.svg',
    },
    {
        id: 964,
        name: 'IQ',
        displayText: 'IQ(+964)',
        locale: 'es-ES',
        flag: '/img/flags/iq.svg',
    },
    {
        id: 353,
        name: 'IE',
        displayText: 'IE(+353)',
        locale: 'es-ES',
        flag: '/img/flags/ie.svg',
    },
    {
        id: 98,
        name: 'IR',
        displayText: 'IR(+98)',
        locale: 'es-ES',
        flag: '/img/flags/ir.svg',
    },
    {
        id: 354,
        name: 'IS',
        displayText: 'IS(+354)',
        locale: 'es-ES',
        flag: '/img/flags/is.svg',
    },
    {
        id: 1006,
        name: 'KY',
        displayText: 'KY(+1006)',
        locale: 'es-ES',
        flag: '/img/flags/ky.svg',
    },
    {
        id: 682,
        name: 'CK',
        displayText: 'CK(+682)',
        locale: 'es-ES',
        flag: '/img/flags/ck.svg',
    },
    {
        id: 692,
        name: 'MH',
        displayText: 'MH(+692)',
        locale: 'es-ES',
        flag: '/img/flags/mh.svg',
    },
    {
        id: 677,
        name: 'SB',
        displayText: 'SB(+677)',
        locale: 'es-ES',
        flag: '/img/flags/sb.svg',
    },
    {
        id: 284,
        name: 'VG',
        displayText: 'VG(+284)',
        locale: 'es-ES',
        flag: '/img/flags/vg.svg',
    },
    {
        id: 972,
        name: 'IL',
        displayText: 'IL(+972)',
        locale: 'es-ES',
        flag: '/img/flags/il.svg',
    },
    {
        id: 39,
        name: 'IT',
        displayText: 'IT(+39)',
        locale: 'es-ES',
        flag: '/img/flags/it.svg',
    },
    {
        id: 1010,
        name: 'JM',
        displayText: 'JM(+1010)',
        locale: 'es-ES',
        flag: '/img/flags/jm.svg',
    },
    {
        id: 81,
        name: 'JP',
        displayText: 'JP(+81)',
        locale: 'es-ES',
        flag: '/img/flags/jp.svg',
    },
    {
        id: 962,
        name: 'JO',
        displayText: 'JO(+962)',
        locale: 'es-ES',
        flag: '/img/flags/jo.svg',
    },
    {
        id: 254,
        name: 'KE',
        displayText: 'KE(+254)',
        locale: 'es-ES',
        flag: '/img/flags/ke.svg',
    },
    {
        id: 686,
        name: 'KI',
        displayText: 'KI(+686)',
        locale: 'es-ES',
        flag: '/img/flags/ki.svg',
    },
    {
        id: 965,
        name: 'KW',
        displayText: 'KW(+965)',
        locale: 'es-ES',
        flag: '/img/flags/kw.svg',
    },
    {
        id: 856,
        name: 'LA',
        displayText: 'LA(+856)',
        locale: 'es-ES',
        flag: '/img/flags/la.svg',
    },
    {
        id: 266,
        name: 'LS',
        displayText: 'LS(+266)',
        locale: 'es-ES',
        flag: '/img/flags/ls.svg',
    },
    {
        id: 231,
        name: 'LR',
        displayText: 'LR(+231)',
        locale: 'es-ES',
        flag: '/img/flags/lr.svg',
    },
    {
        id: 218,
        name: 'LY',
        displayText: 'LY(+218)',
        locale: 'es-ES',
        flag: '/img/flags/ly.svg',
    },
    {
        id: 417,
        name: 'LI',
        displayText: 'LI(+417)',
        locale: 'es-ES',
        flag: '/img/flags/li.svg',
    },
    {
        id: 370,
        name: 'LT',
        displayText: 'LT(+370)',
        locale: 'es-ES',
        flag: '/img/flags/lt.svg',
    },
    {
        id: 352,
        name: 'LU',
        displayText: 'LU(+352)',
        locale: 'es-ES',
        flag: '/img/flags/lu.svg',
    },
    {
        id: 853,
        name: 'MO',
        displayText: 'MO(+853)',
        locale: 'es-ES',
        flag: '/img/flags/mo.svg',
    },
    {
        id: 261,
        name: 'MG',
        displayText: 'MG(+261)',
        locale: 'es-ES',
        flag: '/img/flags/mg.svg',
    },
    {
        id: 60,
        name: 'MY',
        displayText: 'MY(+60)',
        locale: 'es-ES',
        flag: '/img/flags/my.svg',
    },
    {
        id: 265,
        name: 'MW',
        displayText: 'MW(+265)',
        locale: 'es-ES',
        flag: '/img/flags/mw.svg',
    },
    {
        id: 960,
        name: 'MV',
        displayText: 'MV(+960)',
        locale: 'es-ES',
        flag: '/img/flags/mv.svg',
    },
    {
        id: 356,
        name: 'MT',
        displayText: 'MT(+356)',
        locale: 'es-ES',
        flag: '/img/flags/mt.svg',
    },
    {
        id: 223,
        name: 'ML',
        displayText: 'ML(+223)',
        locale: 'es-ES',
        flag: '/img/flags/ml.svg',
    },
    {
        id: 212,
        name: 'MA',
        displayText: 'MA(+212)',
        locale: 'es-ES',
        flag: '/img/flags/ma.svg',
    },
    {
        id: 230,
        name: 'MU',
        displayText: 'MU(+230)',
        locale: 'es-ES',
        flag: '/img/flags/mu.svg',
    },
    {
        id: 222,
        name: 'MR',
        displayText: 'MR(+222)',
        locale: 'es-ES',
        flag: '/img/flags/mr.svg',
    },
    {
        id: 2696,
        name: 'YT',
        displayText: 'YT(+2696)',
        locale: 'es-ES',
        flag: '/img/flags/yt.svg',
    },
    {
        id: 691,
        name: 'FM',
        displayText: 'FM(+691)',
        locale: 'es-ES',
        flag: '/img/flags/fm.svg',
    },
    {
        id: 976,
        name: 'MN',
        displayText: 'MN(+976)',
        locale: 'es-ES',
        flag: '/img/flags/mn.svg',
    },
    {
        id: 1011,
        name: 'MS',
        displayText: 'MS(+1011)',
        locale: 'es-ES',
        flag: '/img/flags/ms.svg',
    },
    {
        id: 258,
        name: 'MZ',
        displayText: 'MZ(+258)',
        locale: 'es-ES',
        flag: '/img/flags/mz.svg',
    },
    {
        id: 95,
        name: 'MM',
        displayText: 'MM(+95)',
        locale: 'es-ES',
        flag: '/img/flags/mm.svg',
    },
    {
        id: 52,
        name: 'MX',
        displayText: 'MX(+52)',
        locale: 'es-ES',
        flag: '/img/flags/mx.svg',
    },
    {
        id: 377,
        name: 'MC',
        displayText: 'MC(+377)',
        locale: 'es-ES',
        flag: '/img/flags/mc.svg',
    },
    {
        id: 264,
        name: 'NA',
        displayText: 'NA(+264)',
        locale: 'es-ES',
        flag: '/img/flags/na.svg',
    },
    {
        id: 674,
        name: 'NR',
        displayText: 'NR(+674)',
        locale: 'es-ES',
        flag: '/img/flags/nr.svg',
    },
    {
        id: 977,
        name: 'NP',
        displayText: 'NP(+977)',
        locale: 'es-ES',
        flag: '/img/flags/np.svg',
    },
    {
        id: 505,
        name: 'NI',
        displayText: 'NI(+505)',
        locale: 'es-ES',
        flag: '/img/flags/ni.svg',
    },
    {
        id: 227,
        name: 'NE',
        displayText: 'NE(+227)',
        locale: 'es-ES',
        flag: '/img/flags/ne.svg',
    },
    {
        id: 234,
        name: 'NG',
        displayText: 'NG(+234)',
        locale: 'es-ES',
        flag: '/img/flags/ng.svg',
    },
    {
        id: 683,
        name: 'NU',
        displayText: 'NU(+683)',
        locale: 'es-ES',
        flag: '/img/flags/nu.svg',
    },
    {
        id: 47,
        name: 'NO',
        displayText: 'NO(+47)',
        locale: 'es-ES',
        flag: '/img/flags/no.svg',
    },
    {
        id: 687,
        name: 'NC',
        displayText: 'NC(+687)',
        locale: 'es-ES',
        flag: '/img/flags/nc.svg',
    },
    {
        id: 64,
        name: 'NZ',
        displayText: 'NZ(+64)',
        locale: 'es-ES',
        flag: '/img/flags/nz.svg',
    },
    {
        id: 968,
        name: 'OM',
        displayText: 'OM(+968)',
        locale: 'es-ES',
        flag: '/img/flags/om.svg',
    },
    {
        id: 92,
        name: 'PK',
        displayText: 'PK(+92)',
        locale: 'es-ES',
        flag: '/img/flags/pk.svg',
    },
    {
        id: 507,
        name: 'PA',
        displayText: 'PA(+507)',
        locale: 'es-ES',
        flag: '/img/flags/pa.svg',
    },
    {
        id: 595,
        name: 'PY',
        displayText: 'PY(+595)',
        locale: 'es-ES',
        flag: '/img/flags/py.svg',
    },
    {
        id: 51,
        name: 'PE',
        displayText: 'PE(+51)',
        locale: 'es-ES',
        flag: '/img/flags/pe.svg',
    },
    {
        id: 689,
        name: 'PF',
        displayText: 'PF(+689)',
        locale: 'es-ES',
        flag: '/img/flags/pf.svg',
    },
    {
        id: 48,
        name: 'PL',
        displayText: 'PL(+48)',
        locale: 'es-ES',
        flag: '/img/flags/pl.svg',
    },
    {
        id: 351,
        name: 'PT',
        displayText: 'PT(+351)',
        locale: 'es-ES',
        flag: '/img/flags/pt.svg',
    },
    {
        id: 1787,
        name: 'PR',
        displayText: 'PR(+1787)',
        locale: 'es-ES',
        flag: '/img/flags/pr.svg',
    },
    {
        id: 974,
        name: 'QA',
        displayText: 'QA(+974)',
        locale: 'es-ES',
        flag: '/img/flags/qa.svg',
    },
    {
        id: 44,
        name: 'GB',
        displayText: 'GB(+44)',
        locale: 'es-ES',
        flag: '/img/flags/gb.svg',
    },
    {
        id: 42,
        name: 'CZ',
        displayText: 'CZ(+42)',
        locale: 'es-ES',
        flag: '/img/flags/cz.svg',
    },
    {
        id: 1008,
        name: 'DO',
        displayText: 'DO(+1008)',
        locale: 'es-ES',
        flag: '/img/flags/do.svg',
    },
    {
        id: 262,
        name: 'RE',
        displayText: 'RE(+262)',
        locale: 'es-ES',
        flag: '/img/flags/re.svg',
    },
    {
        id: 40,
        name: 'RO',
        displayText: 'RO(+40)',
        locale: 'es-ES',
        flag: '/img/flags/ro.svg',
    },
    {
        id: 684,
        name: 'WS',
        displayText: 'WS(+684)',
        locale: 'es-ES',
        flag: '/img/flags/ws.svg',
    },
    {
        id: 684,
        name: 'AS',
        displayText: 'AS(+684)',
        locale: 'es-ES',
        flag: '/img/flags/as.svg',
    },
    {
        id: 378,
        name: 'SM',
        displayText: 'SM(+378)',
        locale: 'es-ES',
        flag: '/img/flags/sm.svg',
    },
    {
        id: 221,
        name: 'SN',
        displayText: 'SN(+221)',
        locale: 'es-ES',
        flag: '/img/flags/sn.svg',
    },
    {
        id: 248,
        name: 'SC',
        displayText: 'SC(+248)',
        locale: 'es-ES',
        flag: '/img/flags/sc.svg',
    },
    {
        id: 232,
        name: 'SL',
        displayText: 'SL(+232)',
        locale: 'es-ES',
        flag: '/img/flags/sl.svg',
    },
    {
        id: 65,
        name: 'SG',
        displayText: 'SG(+65)',
        locale: 'es-ES',
        flag: '/img/flags/sg.svg',
    },
    {
        id: 963,
        name: 'SY',
        displayText: 'SY(+963)',
        locale: 'es-ES',
        flag: '/img/flags/sy.svg',
    },
    {
        id: 252,
        name: 'SO',
        displayText: 'SO(+252)',
        locale: 'es-ES',
        flag: '/img/flags/so.svg',
    },
    {
        id: 94,
        name: 'LK',
        displayText: 'LK(+94)',
        locale: 'es-ES',
        flag: '/img/flags/lk.svg',
    },
    {
        id: 27,
        name: 'ZA',
        displayText: 'ZA(+27)',
        locale: 'es-ES',
        flag: '/img/flags/za.svg',
    },
    {
        id: 249,
        name: 'SD',
        displayText: 'SD(+249)',
        locale: 'es-ES',
        flag: '/img/flags/sd.svg',
    },
    {
        id: 46,
        name: 'SE',
        displayText: 'SE(+46)',
        locale: 'es-ES',
        flag: '/img/flags/se.svg',
    },
    {
        id: 41,
        name: 'CH',
        displayText: 'CH(+41)',
        locale: 'es-ES',
        flag: '/img/flags/ch.svg',
    },
    {
        id: 597,
        name: 'SR',
        displayText: 'SR(+597)',
        locale: 'es-ES',
        flag: '/img/flags/sr.svg',
    },
    {
        id: 66,
        name: 'TH',
        displayText: 'TH(+66)',
        locale: 'es-ES',
        flag: '/img/flags/th.svg',
    },
    {
        id: 886,
        name: 'TW',
        displayText: 'TW(+886)',
        locale: 'es-ES',
        flag: '/img/flags/tw.svg',
    },
    {
        id: 255,
        name: 'TZ',
        displayText: 'TZ(+255)',
        locale: 'es-ES',
        flag: '/img/flags/tz.svg',
    },
    {
        id: 228,
        name: 'TG',
        displayText: 'TG(+228)',
        locale: 'es-ES',
        flag: '/img/flags/tg.svg',
    },
    {
        id: 676,
        name: 'TO',
        displayText: 'TO(+676)',
        locale: 'es-ES',
        flag: '/img/flags/to.svg',
    },
    {
        id: 1016,
        name: 'TT',
        displayText: 'TT(+1016)',
        locale: 'es-ES',
        flag: '/img/flags/tt.svg',
    },
    {
        id: 993,
        name: 'TM',
        displayText: 'TM(+993)',
        locale: 'es-ES',
        flag: '/img/flags/tm.svg',
    },
    {
        id: 688,
        name: 'TV',
        displayText: 'TV(+688)',
        locale: 'es-ES',
        flag: '/img/flags/tv.svg',
    },
    {
        id: 256,
        name: 'UG',
        displayText: 'UG(+256)',
        locale: 'es-ES',
        flag: '/img/flags/ug.svg',
    },
    {
        id: 598,
        name: 'UY',
        displayText: 'UY(+598)',
        locale: 'es-ES',
        flag: '/img/flags/uy.svg',
    },
    {
        id: 737,
        name: 'UZ',
        displayText: 'UZ(+737)',
        locale: 'es-ES',
        flag: '/img/flags/uz.svg',
    },
    {
        id: 7377,
        name: 'VU',
        displayText: 'VU(+7377)',
        locale: 'es-ES',
        flag: '/img/flags/vu.svg',
    },
    {
        id: 58,
        name: 'VE',
        displayText: 'VE(+58)',
        locale: 'es-ES',
        flag: '/img/flags/ve.svg',
    },
    {
        id: 84,
        name: 'VN',
        displayText: 'VN(+84)',
        locale: 'es-ES',
        flag: '/img/flags/vn.svg',
    },
    {
        id: 681,
        name: 'WF',
        displayText: 'WF(+681)',
        locale: 'es-ES',
        flag: '/img/flags/wf.svg',
    },
    {
        id: 967,
        name: 'YE',
        displayText: 'YE(+967)',
        locale: 'es-ES',
        flag: '/img/flags/ye.svg',
    },
    {
        id: 260,
        name: 'ZM',
        displayText: 'ZM(+260)',
        locale: 'es-ES',
        flag: '/img/flags/zm.svg',
    },
]
