name: Push

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: cleanup
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: docker://sonarsource/sonar-scanner-cli:latest
        with:
          args: >-
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
